### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by expectopatronum** [meinardmueller/libfmp#1]
Hi everyone,
I am currently reviewing your JOSS submission [here](https://github.com/openjournals/joss-reviews/issues/3326). 

I don't think I can tick "Automated tests" yet. I found the script "test_examples.py" and if I executed it, nothing happens. I expect that this means there are no errors. However, it would be great to have some output if everything is alright, e.g. using [unittest](https://docs.python.org/3/library/unittest.html) could help with that.
And another minor remark, it would be great to have a (sub)section in the README that instructs the user about how the tests should be executed, and in the ideal case also describes what is covered by the tests, because for me it looks like only one function per subpackage is covered.

Best regards
Verena

**Comment by fzalkow** [comment]
Dear Verena,

Many thanks for your review and the feedback. We added a section in the README that describes our philosophy regarding tests.

libfmp is special in the sense that it originates from the FMP notebooks.

https://www.audiolabs-erlangen.de/FMP 

There, the correct input-output behavior of the functions is described together with extensive explanations. We consider this an "enriched" replacement for traditional unit tests. We are aware that this corresponds to a somewhat "manual" testing procedure. As far as I understand the JOSS review checklists, manual testing steps are also acceptable. We do not plan to provide comprehensive automated unit tests.

The small test script can be executed with [pytest](https://pytest.org/) (instead of [unittest](https://docs.python.org/3/library/unittest.html)) as described in the new README section. Librosa has inspired us to use this package for testing.

Best,

Frank

**Comment by expectopatronum** [comment]
Hi Frank,
thanks a lot for explaining your design choices regarding testing! Sounds good to me!

> The small test script can be executed with pytest (instead of unittest) as described in the new README section. Librosa has inspired us to use this package for testing.

I wasn't aware of pytest, thanks for the additional description. Works for me!

Best regards
Verena
