### ISSUE TITLE
issue a new release

### ISSUE THREAD

**Issue by faroit** [meinardmueller/libfmp#4]
the release on pypi still has frozen dependencies which break many environments. Creating a new release could potentially solves these issues....

https://github.com/openjournals/joss-reviews/issues/3434

**Comment by fzalkow** [comment]
Hi @farot,

You are right. We wanted to make a new release as soon as the JOSS review process for libfmp nears completion. Since this is the case now, I just created a new release, version 1.2.0.

Github release: https://github.com/meinardmueller/libfmp/releases/tag/v1.2.0
PyPi Package: https://pypi.org/project/libfmp/1.2.0/

Best,

Frank

**Comment by fzalkow** [comment]
I consider this solved. Please reopen the issue if any problems persist.
